name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Create Stuff
        run: |
          # Temporary file to hold the concatenation
          temp_file=$(mktemp)
          # Iterate through all markdown files in the current directory
          for file in *.md; do
            # Ensure that each file starts on a new page by appending a page break
            echo -e "\n\pagebreak\n" >> "$temp_file"
            # Concatenate the current file content to the temporary file
            cat "$file" >> "$temp_file"
          done

      - uses: docker://pandoc/latex:2.9
        with:
          args: \"$temp_file" -o output.pdf -f markdown-implicit_figures
      - name: Clean Up
        run: rm -rf "$temp_file"
      - name: Commit
        run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" && git config --global user.name "github-actions[bot]" && git add . && git commit -m "Auto Updated Blog Posts" && git push
      
